[tools]
pre-commit = "4.5.1"
python = "3.14"
terraform = "1.14.4"
terraform-docs = "0.21.0"

[tasks.terraform-docs]
description = "Generates terraform docs for all modules"
run = "terraform-docs markdown table --output-file README.md ."
