[tools]
pre-commit = "4.3.0"
python = "3.14"
terraform = "1.13.4"
terraform-docs = "0.20.0"

[tasks.terraform-docs]
description = "Generates terraform docs for all modules"
run = "terraform-docs markdown table --output-file README.md ."
